### ISSUE TITLE
Logtable strings are not correctly escaped 

### ISSUE THREAD

**Issue by tornede** [tornede/py_experimenter#117]
* PyExperimenter version: 1.2.0
* Python version: 3.9.16
* Operating System: MacOS

### Description

The types of keyfields, resultfields and logtable fields are described in the configuration file (VARCHAR if not further specified by user). When some value is processed to be written in a logtable, neither a type check is done, nor a string conversion to include the needed "..." for all strings for the SQL statement. 

#### Used configuration:
```
[PY_EXPERIMENTER]
provider = mysql 
database = py_experimenter
table = bug_logtables_insert_string

keyfields = seed:int
seed = 1,2,3

resultfields = some_string, some_numeric:DECIMAL
resultfields.timestamps = false

logtables = somelogtable:bug_test
bug_test = some_string, some_numeric:DECIMAL
```

#### Used experiment function:
```python
def run_experiment(keyfields: dict, result_processor: ResultProcessor, custom_fields: dict):
    field_values = {
        'some_string' : 'This is a normal Python string',
        'some_numeric' : 1.6
    }

    result_processor.process_results(field_values)
    result_processor.process_logs({
        'somelogtable': field_values
    })
```

#### Executed the following code: 
```python
experimenter = PyExperimenter(experiment_configuration_file_path="config/bug_logtables_insert_string.cfg", name='executor')
experimenter.fill_table_from_config()
experimenter.execute(run_ml, max_experiments=1)
```

#### Got following error
```
ERROR:root:Traceback (most recent call last):
File "/Users/tanja/opt/anaconda3/envs/codecarbon/lib/python3.9/site-packages/py_experimenter/database_connector.py", line 52, in execute cursor.execute(sql_statement)
File "/Users/tanja/opt/anaconda3/envs/codecarbon/lib/python3.9/site-packages/mysql/connector/cursor.py", line 617, in execute self._handle_result(self._connection.cmd_query(stmt))
File "/Users/tanja/opt/anaconda3/envs/codecarbon/lib/python3.9/site-packages/mysql/connector/connection.py", line 1046, in cmd_query result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
File "/Users/tanja/opt/anaconda3/envs/codecarbon/lib/python3.9/site-packages/mysql/connector/connection.py", line 824, in _handle_result raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'a normal Python string, 1.6, 1, '2023-04-17 13:21:30')' at line 1
```

5. Database looks like the following. Note that this is the main database table, where the escaping strategy works perfectly fine. 
<img width="1194" alt="Bildschirmfoto 2023-04-17 um 13 26 39" src="https://user-images.githubusercontent.com/47322192/232471776-681a6916-8100-4228-a56d-1b8675ccc9c5.png">

**Comment by LukasFehring** [comment]
This is done, but i will also modify the general behaviour to use prepared statements

**Comment by LukasFehring** [comment]
I adapted the database connector to use prepared statements whenever possible.

Note that they can not be used with conditionals, tablenames, database names and some other values. Therefore not every execute statement was adapted
