### ISSUE TITLE
Include CodeCarbon to PyExperimenter

### ISSUE THREAD

**Issue by tornede** [tornede/py_experimenter#120]
The execution of experiment functions should be tracked with [CodeCarbon](https://github.com/mlco2/codecarbon). The configuration of CodeCarbon should be done within the same file than the one for PyExperimenter, but within a new section. Furthermore, the results should be written into a separate table, similar to logtables. 

# Extend configuration

The experiment configuration will be extended by a section for CodeCarbon. 

```
[PY_EXPERIMENTER]
...

[codecarbon]
... 
```

- [x] [All parameters from CodeCarbon](https://mlco2.github.io/codecarbon/parameters.html#parameters) will be supported.
- [x] Note that [CodeCarbon requires its configuration to be placed in a specific file in a specific folder](https://mlco2.github.io/codecarbon/usage.html#configuration-priority). Therefore, the CodeCarbon section from PyExperimenter experiment configuration file will be copied into a standalone file according to the CodeCarbon documentation.
- [x] An additional parameter `offline_mode` is needed that is responsible to call [online mode](https://mlco2.github.io/codecarbon/usage.html#online-mode) or [offline mode](https://mlco2.github.io/codecarbon/usage.html#offline-mode) of CodeCarbon

### Default CodeCarbon configuration

In case no CodeCarbon configuration is given in PyExperimenter experiment configuration file, use the following: 
```
measure_power_secs = 15
tracking_mode = process
log_level = error
save_to_file = true
output_dir = output/CodeCarbon
```

#### Offline mode

In case of `offline_mode=True` and no specified parameters for offline mode, an exception should be raised giving a concrete example of the parameters needed for offline mode, as well as a link to the [CodeCarbon Documentation](https://mlco2.github.io/codecarbon/parameters.html#specific-parameters-for-offline-mode) 

```
# Parameters for offline mode
country_iso_code = DEU
```

# Update experimenter execution

- [x] The execution call of each experiment will be tracked by CodeCarbon, writing the final results into a separate table `<table_name>_codecarbon` (Note: a single `_` to distinguish from logtables)
- [x] A method to get the CodeCarbon table has to be added: `get_codecarbon()`

**Comment by LukasFehring** [comment]
I just started the implementation of this issue
