### ISSUE TITLE
Improve handling of configuration file and their invalidity

### ISSUE THREAD

**Issue by tornede** [tornede/py_experimenter#139]
- PyExperimenter version: 1.3.0
- Database provider: -
- Python version: -
- Operating System: -

### Description

In case the configuration file is invalid, only a single statement informing about it is returned to the user. It would be preferable to return concrete information WHY the configuration does not fulfill the requirements.

- [x] Within the check, already log the actual problem of the configuration file
- [x] Raise exception afterwards, as already done.
- [x] Catch exception and also shown the original, abstract information to the user referring to the logging statement above, as already done.

**Comment by tornede** [comment]
This issue is related to issues #140 and #89

**Comment by LukasFehring** [comment]
This issue is done.
