### ISSUE TITLE
[Usability] More explicit than key error

### ISSUE THREAD

**Issue by eddiebergman** [tornede/py_experimenter#154]
When setting up a config.conf for the first time, it's a bit hard to know how to set up exactly and prone to some initial mistakes, such as a field being missing.

It would be nice to catch this KeyError and instead give an error message that recommends that maybe this field should be defined in the `config.conf`.

```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[11], line 1
----> 1 experimenter.fill_table_from_config()
      2 experimenter.get_table()

File ~/code/py_experimenter/py_experimenter/experimenter.py:285, in PyExperimenter.fill_table_from_config(self)
    271 """
    272 Adds rows to the database table based on the experiment configuration file.
    273 
   (...)
    282 error is raised.
    283 """
    284 self.dbconnector.create_table_if_not_existing()
--> 285 parameters = utils.get_keyfield_data(self.config)
    286 self.dbconnector.fill_table(parameters=parameters)

File ~/code/py_experimenter/py_experimenter/utils.py:87, in get_keyfield_data(config)
     85 keyfield_data = {}
     86 for keyfield_name, keyfield_type in keyfields:
---> 87     keyfield_values = experiment_config[keyfield_name].replace(' ', '').split(',')
     89     if keyfield_type.startswith('int'):
     90         final_data = _generate_int_data(keyfield_values)

File ~/.pyenv/versions/3.10.8/lib/python3.10/configparser.py:1258, in SectionProxy.__getitem__(self, key)
   1256 def __getitem__(self, key):
   1257     if not self._parser.has_option(self._name, key):
-> 1258         raise KeyError(key)
   1259     return self._parser.get(self._name, key)

KeyError: 'f'
```

**Comment by LukasFehring** [comment]
Hi Eddie,
I am currently reworking how files are being parsed by py-experimenter. There will be two major changes
1. Move to `yaml` for more readable configurations
2. The config file is once parsed in the beginning filling a configuration object creating a single point of failure of config files.

My estimate is that this will elevate this issue. 
I aim to include better error messages as well, but your input would be appreciated.

**Comment by LukasFehring** [comment]
While there might still be errors, unclarities with the new config file structure (we adapted it to yaml) i estimate that most problems are closed by this.
