### ISSUE TITLE
[Feature] `n_jobs` as paramter to `execute()`

### ISSUE THREAD

**Issue by eddiebergman** [tornede/py_experimenter#155]
This was my default idea of how it should be done, not going back and editing the conf file. Having it explicitly hard coded in the conf file might reduce the share-ability of conf files. No a big issue but it might nice to overwrite this conf setting during the call to `execute()`

**Comment by LukasFehring** [comment]
I agree

**Comment by LukasFehring** [comment]
This has been adapted, the change is public
