### ISSUE TITLE
Documentation for distributed execution

### ISSUE THREAD

**Issue by slimyjimmy** [tornede/py_experimenter#175]
Hi there,

in the PyExperimenter paper it says: 

> Once this table has been created, a PyExperimenter instance
can be run on any machine, including a distributed system. Each instance automatically pulls open experiments from
the database, executes the function provided by the user with the corresponding parameters defining the experiment and
writes back the results computed by the function.

Unfortunately, I can't find any documentation on how to configure/run PyExperimenter on aforementioned instances (clients/workers).

Are there any resources on this?

**Comment by tornede** [comment]
Hey Djimon,

It is possible to run PyExperimenter on multiple machines, although we have not explicitly explained how to best do so in the documentation. 

First of all, I suggest to set up a MySQL database, which serves as central organization of all experiments and results, independent on the actual machines that will be used to execute the experiments. 

Second, you need to set up PyExperimenter as usual, as if you would like to execute it on your local machine. Therefore you need:

- [Experiment configuration file](https://tornede.github.io/py_experimenter/usage/experiment_configuration_file.html) defining the database structure and experiments.
- [Database credentials file](https://tornede.github.io/py_experimenter/usage/database_credential_file.html) containing the access information of the MySQL database.
- [Experiment function](https://tornede.github.io/py_experimenter/usage/experiment_function.html) including the actual code to be executed for each experiment.

The following assumes (for simplicity) that the experiments should be executed via a HPC, where each HPC job should execute a single experiment from the MySQL database table. Therefore, you usually have on one hand some kind of submission script for HPC jobs, and on the other hand the actual executable code. Latter would then contain the code to [execute PyExperimenter](https://tornede.github.io/py_experimenter/usage/execution.html) based on the previously defined experiment function, e.g.: 

```python
from py_experimenter.experimenter import PyExperimenter

experimenter = PyExperimenter(
    experiment_configuration_file_path = "path/to/file",
    database_credential_file_path = "path/to/file"
)
experimenter.execute(experiment_function, max_experiments=1)
```

In such way, you would once submit e.g. 50 HPC jobs, each will then execute one of the previously defined experiments from the table. 

A further remark at this point about the database handling in general when working with multiple jobs: it makes sense to have a separate local file to set up the database in advance, and to delete/reset experiments within this local file if needed. 

```python
from py_experimenter.experimenter import PyExperimenter

# experimenter.reset_experiments('error')
experimenter.fill_table_from_config()

```

Does this answer your question / do you miss any information? I would be very happy about any feedback, such that we can soon incorporate this into the documentation.

**Comment by slimyjimmy** [comment]
Hi tornede,

thanks a lot for your reply. That answered my question, thanks!

**Comment by tornede** [comment]
@LukasFehring please transform this into actual documentation unter _Usage_ --> _Distributed Execution_
