### ISSUE TITLE
Adjust requirements.txt to avoid utf-8 problem in mysql connector

### ISSUE THREAD

**Issue by fmohr** [tornede/py_experimenter#52]
With the latest version of the `mysql-connector-python`, one might experiment problems in the charset:

```
DatabaseConnectionError: Character set 'utf8' unsupported
```
or
```
ProgrammingError: Character set 'utf8' unsupported
```

This can be solved by *downgrading* the connector:

```
pip install mysql-connector-python==8.0.29
```

**Comment by tornede** [comment]
mysql-connector-python has been replaced with version 1.3.0, therefore this issue does not exist anymore.
