### ISSUE TITLE
add function to completely erase/reset setup

### ISSUE THREAD

**Issue by fmohr** [tornede/py_experimenter#53]
the experimenter currently has a function to fill in experiments.

However, specifically at the beginning of the workflow, one often experiments a bit. It would be great if there would be a function that completely drops the table and recreates it with the new experiments. Currently, the only way to repair your setup when you change something in the table attributes is to manually delete it.

**Comment by tornede** [comment]
Currently there is a workaround for this via:
```python
experimenter.reset_experiments(status='created')
experimenter.reset_experiments(status='running')
experimenter.reset_experiments(status='error')
experimenter.reset_experiments(status='done')
```

But I agree that a method resetting all experiments (resets all experiment if no status is given)
```python
experimenter.reset_experiments()
```
as well as a method deleting the table 
```python
experimenter.delete_table()
```
are nice additions.

**Comment by tornede** [comment]
> the workaround only works if the table structure did not change. 

True.

> Maybe the function should (also) accept lists of statuses and then you can make the default `["done", "error", "running"]`

Also a nice addition to the method `reset_experiments()`.

> would indeed be nice. And then you could add a shortcut
> 
> ```python
> def full_reset(self):
>    self.delete_table()
>    self.fill_table()
> ```

This only works if you fill your table from a config file. In case you fill the table with one of the other options, this will not be so trivial.

**Comment by tornede** [comment]
Final summary about what will be done:

* Add Enum `ExperimentStatus` for the strings
* Modify `reset_experiments()` to be able to get
  * single status
  * list of status
  * `"all"` to reset all status
* Add method `delete_table()` 

Furthermore, I currently don't see the need for the suggested method `full_reset()`. Either you want to modify the structure of the table itself, which you can do with `delete` and `fill`, or you want to stay with the table structure and just reset some of the experiments.

**Comment by LukasFehring** [comment]
Finished implementation. 

In reset_experiments i worked with pythons *args notation.
