### ISSUE TITLE
experimenter is slow in fetching experiments for 10k+ experiments

### ISSUE THREAD

**Issue by fmohr** [tornede/py_experimenter#59]
I have setups with above 100k experiments. However, even for only 10k experiments, the time until when the `run_experiment` function is called is unacceptably high (something like 30 seconds). This occurs independently of whether `random_order` is true or not.

This happens on my localhost, so it is no network issue.

The time for an experiment to start should be *independent* of the table size (and take less than a second on localhost).

**Comment by tornede** [comment]
This issue should now be solved with the PR #76.
