### ISSUE TITLE
experimenter does not fetch experiments with float key fields

### ISSUE THREAD

**Issue by fmohr** [tornede/py_experimenter#60]
Really weird behavior now: The experimenter correctly gets the table, but does not suck experiments.

## config file
```
[PY_EXPERIMENTER]
provider = mysql 
database = experiments
table = test

keyfields = dataset:int, seed:int, epsilon:float
dataset = 61
seed = 0:2
epsilon = 0.1

cpu.max = 1 

resultfields = analysis:LONGTEXT
resultfields.timestamps = false
```

## Code
```
from py_experimenter.experimenter import PyExperimenter
from py_experimenter.result_processor import ResultProcessor

experimenter = PyExperimenter(config_file="config/experiments-test.cfg")
experimenter.fill_table_from_config()

experimenter.get_table() # will correctly print a table with 3 entries

def f(keyfields: dict, result_processor: ResultProcessor, custom_config):
    print("GO")

experimenter.execute(f, max_experiments=-1, random_order=True) # will do nothing
```

Here is a screenshot:
![image](https://user-images.githubusercontent.com/696908/198027716-3039e8f8-5972-4394-bcd2-29b595ab17c8.png)

**Comment by fmohr** [comment]
I think I could spot the problem: Apparently py_experimenter cannot properly handle keyfields that are `float`. If I change the type of `epsilon` in the above example to `int` it works:
![image](https://user-images.githubusercontent.com/696908/198028213-ab4cfc04-4f53-426d-91d5-d23e1930f293.png)

But this is of course not a proper work-around.

**Comment by tornede** [comment]
Closed this issue due to inactivity. If this issue persists, please reopen the issue.
