### ISSUE TITLE
Add Database Logging Functionality

### ISSUE THREAD

**Issue by tornede** [tornede/py_experimenter#63]
The general idea is to add the functionality to log values for a single field over time, like the `new_best_performance` observed, or information about some epochs like its `runtime` or `performance`. Therefore `logtables` are introduced, each being able to log predefined information over time.

# Example

Having a look at a concrete example, one would like to have the main table `experiment_example` with

- `dataset`
- `seed` (both keyfields), as well as 
- `pipeline`, 
- `accuracy`, and 
- `f1` (all three resultfields).

And additionally logged information within the run of each experiment will be stored in separated tables, each having multiple entries for each `experiment_id` for different `timestamp`s. Each entry of a `logtable` is automatically associated with the according `experiment_id` and a `timestamp`. 

- `experiment_example__new_best_performance` will store
  - `experiment_id`
  - `timestamp`
  - `new_best_performance`
- `experiment_example__epochs` will store
  - `experiment_id`
  - `timestamp`
  - `runtime`
  - `performance`

# Configuration File

The `configuration file` could look like in the following. `logtables` is the keyword for defining new tables for logging, supporting two types:

- Usual SQL type, like `FLOAT`
- Complex types, which has to have a unique name, like `LogEpochs` and can consist of multiple SQL types like `FLOAT` or `INT`

Each item in `logtables` (be it a simple or complex type) will create an entirely new table. This needs to be kept in mind for aggregating the results, as needlessly splitting up logs over multiple tables will need to costly joins when aggregating.

```
[PY_EXPERIMENTER]
provider = sqlite
database = experiment_database
table = experiment_example

keyfields = dataset, seed:int(1)
resultfields = pipeline:LONGTEXT, accuracy:FLOAT, f1:FLOAT
logtables = new_best_performance:INT, epochs:LogEpochs                    # <- This is new
LogEpochs = runtime:FLOAT, performance:FLOAT                              # <- This is new

[CUSTOM]
output_folder = output/
```

# Usage

The `ResultProcessor` will get the new method `process_logs()` to handle the logging. It gets a dict with the `logtable` name as keys and depending on the type the value:
- Usual SQL types: value
- Complex types: dict of complex type names and values

```python
result_processor.process_logs({
    'new_best_performance': 0.86,
    'epochs': {
        'runtime': 42,
        'performance': 0.79
    }
}) 
```

# Performance
To avoid ddossing the own database, it is necessary to buffer the logging (dynamically).

**Comment by helegraf** [comment]
Thanks for writing up our discussion!

I think some points can be clarified/ emphasized a little:
- `logtables` is the keyword for defining new tables for logging. 
- Each item in logtables (be it a simple or complex type) will create an entirely new table. This needs to be kept in mind for aggregating the results, as needlessly splitting up logs over multiple tables will need to costly joins when aggregating.
- I still don't think `complex type` is the best descriptor for a logtable containing multiple logs. It suggests that the fields in the table must somehow be related, which they don't. In the documentation, it might be more intuitive to describe the setup with a logtable containing multiple fields first, and then explain that the other case ('Usual SQL types'  is a shortcut in case there is a logtable with only one field (apart from `experiment_id` and `timestamp`).

**Comment by tornede** [comment]
@helegraf Thanks for the remarks, I updated the issue according to the first two points. 

Regarding 3.) I would like to avoid having another `field` meaning as this could be confusing. Apart from that, the log fields within a single `logtable` ARE related at least in terms of frequency, as one can assume that all those fields are filled at the same time, otherwise one would create separated log tables for each field

**Comment by LukasFehring** [comment]
I am currently working on the implementation of this issue

**Comment by LukasFehring** [comment]
Án implementation that disregards the shorthand notation has been finished. The shorthand notation will be added shortly. However, due to an unrelated PoetryException (Problem with MACOS) the pipeline fails.

**Comment by LukasFehring** [comment]
Rebased Branch on #75 since we already needed the experiment_id as a foreign key in this branch.

**Comment by LukasFehring** [comment]
The following problems exist in the current implementation:

- [ ] The columns should be in the following order: 
1. ID
2. experiment_id
3. timestamp
4. Everything else
- [ ] The database table raises several errors. 
1. Check whether this issue depends on the used mysql database by executing the test case on a different DB.
2. Fix the issues
