### ISSUE TITLE
Update Experiment Handling

### ISSUE THREAD

**Issue by tornede** [tornede/py_experimenter#71]
The current implementation of the execution of multiple experiments does not scale well for a large number of experiments. The reason is how the given `max_experiments` (e.g. `=5`) are selected and executed. First the complete table is pulled, then locally it is shuffled and the top `5` experiments are selected for execution. But the execution is usually not parallel, but sequential, may resulting in an overlap with another `PyExperimenter` instance. At the end it could be that not the full amount of experiments are executed.

# Solution
* The experiment configuration field `cpu.max` will be renamed to `number_parallel_experiments`. 
* Rename `max_experiments` to `max_number_experiments_to_execute`
* `PyExperimenter.execute()` will spawn as many worker as defined by `number_parallel_experiments`
* The open experiment will not be pulled once in advance, but within each call of the `PyExperimenter._execution_wrapper()`. This will be completely handled by the `SELECT` call, including the `randomize` (if given), and limits the results to `1`. In the same transaction of the pull of an open experiment, its status will be set to `running`. 
* An open experiment will only be pulled if `max_number_experiments_to_execute` has not been reached (except for `-1`)

# Impacted Issues
* #59 
* #67

**Comment by LukasFehring** [comment]
I am currently working on this issue. The solution is detailed above by @tornede.

**Comment by LukasFehring** [comment]
The documentation is updated. Therefore, I opened a merge request.
