### ISSUE TITLE
Fetching experiments does not work anymore on MySQL with certain versions

### ISSUE THREAD

**Issue by fmohr** [tornede/py_experimenter#80]
Hi,

with the new version of the experimenter (1.1.0) when running the `execute` function I now receive the following error message (without stack trace or anything):

```bash
ERROR:root:error 
 MySQL server version (5, 5, 5) does not support this feature raised. 
 Please check if fill_table() was called correctly.
```

Not sure where the error is risen exactly. My version is `Server version: 10.9.3-MariaDB Arch Linux`

The error does *not* occur on plain MySQL. Here, I have one with version `mysql  Ver 8.0.20 for Linux on x86_64 (MySQL Community Server - GPL)`.

MariaDB is usually a largely compatible equivalent for MySQL (on arch linux it *is* the mysql replacement, because there is no official mysql package). Have you any idea which functionality used from MySQL might this behavior when using MariaDB instead?

**Comment by fmohr** [comment]
Apparently that happens in the `database_connector`. Maybe I will try to throw the original exception in the part
```python
    def get_experiment_configuration(self, random_order: bool):
        try:
            experiment_id, description, values = self._pull_open_experiment(random_order)
        except IndexError as e:
            raise NoExperimentsLeftException("No experiments left to execute")
        except Exception as e:
            raise DatabaseConnectionError(f'error \n {e} raised. \n Please check if fill_table() was called correctly.')
```
in order to see the stack trace and which statement causes this problem.

**Comment by fmohr** [comment]
Ok I could trace it back. The problem is in line 65 of `database_connector_mysql`:
```python
    def _start_transaction(self, connection, readonly=False):
        connection.start_transaction(readonly=readonly)
```
Apparently, this does not work properly with MariaDB. There is a dedicated connector for `mariadb`. So this maybe calls for another connector to support MariaDB. If I can find some time I could try to implement that myself. In the first place, this could be a copy/paste from the mysql connector, and only this part is being changed.

I would still like to mention that no transactions are generally necessary for this. In the Java version we have it without transactions.

**Comment by LukasFehring** [comment]
Why do you think transactions are not necessary here?

We're here dealing with the problem that two processes might run on separate machines (they do not know each other) and pull an experiment from the database. If we do not use transactions, they might pull the same experiment unless the pull and status modification are done in one transaction.

**Comment by fmohr** [comment]
Here is the code from the Java version. It does not use transactions but applies the `where` clause in the update statement and returns the id.

```java
		/*
		 * Build a query to update a random unstarted experiment and fetch the updated id:
		 */
		StringBuilder sb = new StringBuilder();
		sb.append("UPDATE ");
		sb.append(this.tablename);
		sb.append(" AS target_table ");

		// Fields to be updated are `time_started`=(now) and `host`=(host name of this machine):
		sb.append("SET target_table.");
		sb.append(FIELD_TIME_START);
		sb.append(" = '");
		sb.append(new SimpleDateFormat(DATE_FORMAT).format(new Date()));
		sb.append("', target_table.");
		sb.append(FIELD_HOST);
		sb.append(" = '");
		sb.append(this.cachedHost);
		sb.append("', target_table.");
		sb.append(FIELD_EXECUTOR);
		sb.append(" = '");
		sb.append(executorInfo);
		sb.append("' ");

		// We need the id of the updated row.
		// The trick is to tell mysql to update the last insert id with the single affected row:
		// See: https://stackoverflow.com/questions/1388025
		// This is a MySQL specific solution.
		sb.append(" WHERE target_table.time_started IS NULL" + " AND last_insert_id(target_table.experiment_id)" + " LIMIT 1");
```

Here is the [link to the full code]( https://github.com/starlibs/AILibs/blob/b355727b4cdeb5eda09a8fac15eca731bd8be5fd/JAICore/jaicore-experiments/src/main/java/ai/libs/jaicore/experiments/databasehandle/AExperimenterSQLHandle.java#L294). Has been tested exhaustively over years in practice.

**Comment by tornede** [comment]
Closed this issue due to inactivity. If this issue persists, please reopen the issue.
